In [1]:
import numpy as np

0D TENSOR/ SCALER

In [2]:
a = np.array(4)

In [3]:
a

array(4)

In [4]:
type(a)

numpy.ndarray

In [5]:
a.ndim

0

 1D TENSOR/ VECTOR

In [6]:
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [10]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
mat.ndim

2

In [12]:
three = np.array ([[[10,11,12],[13,14,15],[16,17,18]]])

In [13]:
three

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
three.ndim

3

In [17]:
 four = np.array ([[[[10,11,12],[13,14,15],[16,17,18],[19,20,21]]]])

In [18]:
four.ndim

4

In [20]:
five = np.array ([[[[[10,11,12],[13,14,15],[16,17,18],[19,20,21]]]]])

In [21]:
five

array([[[[[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18],
          [19, 20, 21]]]]])

In [22]:
five.ndim

5

In [23]:
type(five)

numpy.ndarray