In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("customer.csv")

In [4]:
df.sample(5)

age  gender   review education purchased
18   19    Male     Good    School        No
11   74    Male     Good        UG       Yes
5    31  Female  Average    School       Yes
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No

In [5]:
df = df.iloc[:,2:]

In [65]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [64]:
x.head()

review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

In [27]:
y.shape

(50,)

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [59]:
x_train, x_test

(     review education
 33     Good        PG
 35     Poor    School
 26     Poor        PG
 34  Average    School
 18     Good    School
 7      Poor    School
 14     Poor        PG
 45     Poor        PG
 48     Good        UG
 29  Average        UG
 15     Poor        UG
 30  Average        UG
 32  Average        UG
 16     Poor        UG
 42     Good        PG
 20  Average    School
 43     Poor        PG
 8   Average        UG
 13  Average    School
 25     Good    School
 5   Average    School
 17     Poor        UG
 40     Good    School
 49     Good        UG
 1      Poor        UG
 12     Poor    School
 37  Average        PG
 24  Average        PG
 6      Good    School
 23     Good    School
 36     Good        UG
 21  Average        PG
 19     Poor        PG
 9      Good        UG
 39     Poor        PG
 46     Poor        PG
 3      Good        PG
 0   Average    School
 47     Good        PG
 44  Average        UG,
      review education
 28     Poor    School
 11     Go

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [47]:
oe = OrdinalEncoder(categories = [["Poor","Average","Good"],["School","UG","PG"]])

In [48]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [62]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [63]:
x_train,x_test

(array([[2., 2.],
        [0., 0.],
        [0., 2.],
        [1., 0.],
        [2., 0.],
        [0., 0.],
        [0., 2.],
        [0., 2.],
        [2., 1.],
        [1., 1.],
        [0., 1.],
        [1., 1.],
        [1., 1.],
        [0., 1.],
        [2., 2.],
        [1., 0.],
        [0., 2.],
        [1., 1.],
        [1., 0.],
        [2., 0.],
        [1., 0.],
        [0., 1.],
        [2., 0.],
        [2., 1.],
        [0., 1.],
        [0., 0.],
        [1., 2.],
        [1., 2.],
        [2., 0.],
        [2., 0.],
        [2., 1.],
        [1., 2.],
        [0., 2.],
        [2., 1.],
        [0., 2.],
        [0., 2.],
        [2., 2.],
        [1., 0.],
        [2., 2.],
        [1., 1.]]),
 array([[0., 0.],
        [2., 1.],
        [2., 1.],
        [2., 2.],
        [2., 2.],
        [0., 2.],
        [2., 0.],
        [0., 0.],
        [0., 2.],
        [1., 1.]]))

In [71]:
x_train = pd.DataFrame(x_train ,columns= ["review","education"])

In [73]:
x_train

review  education
0      2.0        2.0
1      0.0        0.0
2      0.0        2.0
3      1.0        0.0
4      2.0        0.0
5      0.0        0.0
6      0.0        2.0
7      0.0        2.0
8      2.0        1.0
9      1.0        1.0
10     0.0        1.0
11     1.0        1.0
12     1.0        1.0
13     0.0        1.0
14     2.0        2.0
15     1.0        0.0
16     0.0        2.0
17     1.0        1.0
18     1.0        0.0
19     2.0        0.0
20     1.0        0.0
21     0.0        1.0
22     2.0        0.0
23     2.0        1.0
24     0.0        1.0
25     0.0        0.0
26     1.0        2.0
27     1.0        2.0
28     2.0        0.0
29     2.0        0.0
30     2.0        1.0
31     1.0        2.0
32     0.0        2.0
33     2.0        1.0
34     0.0        2.0
35     0.0        2.0
36     2.0        2.0
37     1.0        0.0
38     2.0        2.0
39     1.0        1.0

In [74]:
x_test = pd.DataFrame(x_test ,columns= ["review","education"])

In [75]:
x_test

review  education
0     0.0        0.0
1     2.0        1.0
2     2.0        1.0
3     2.0        2.0
4     2.0        2.0
5     0.0        2.0
6     2.0        0.0
7     0.0        0.0
8     0.0        2.0
9     1.0        1.0

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
le = LabelEncoder()

In [112]:
le.fit(y_train)


LabelEncoder()

In [113]:
le.classes_

array([0, 1], dtype=int64)

In [114]:
y_train = le.transform(y_train)
y_test = le.tranform(y_test)


AttributeError: 'LabelEncoder' object has no attribute 'tranform'

In [115]:
y_test.replace({'No': 0}, {"Yes":1},inplace=True)

y_test = le.transform(y_test)

AttributeError: 'Series' object has no attribute '_replace_columnwise'

In [126]:


# Assuming Y_test is a pandas Series
# y_test = y_test.replace('No', 0)
y_test = y_test.astype(str)  # Convert all elements to strings


# Create an instance of LabelEncoder
le = LabelEncoder()

# Fit the encoder to the data
le.fit(y_test)

# Perform label encoding
y_test = le.transform(y_test)


In [123]:
y_test

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0])

In [124]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [125]:
y_test

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0])